name: Deploy Laravel Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.id_ed25519 }}

      - name: Deploy to Server
        run: |
          ssh user@server "cd /home/jaksws/web/jaksws.com/public_html && git pull origin master && composer install && php artisan migrate --force"
